repos:
- repo: local
  hooks:
  - id: pylint
    name: Pylint
    entry: poetry run pylint ./vk_extract_audio_from_video_bot/
    language: system
    types:
      - python
    require_serial: true
    
  - id: ruff
    name: ruff
    entry: poetry run ruff check . --fix
    language: system
    types:
      - python
    require_serial: true
