repos:
- repo: local
  hooks:

  - id: ruff
    name: ruff
    entry: poetry run ruff check
    language: system
    types:
      - python
    require_serial: true

  - id: pylint
    name: Pylint
    entry: poetry run pylint ./vk_extract_audio_bot/
    language: system
    types:
      - python
    require_serial: true
